/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as _authenticatedRouteImport } from './routes/__authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as _authenticatedIndexRouteImport } from './routes/__authenticated/index'
import { Route as _authenticatedSettingsRouteImport } from './routes/__authenticated/settings'
import { Route as _authenticatedTasksIndexRouteImport } from './routes/__authenticated/tasks/index'
import { Route as _authenticatedTasksIdRouteImport } from './routes/__authenticated/tasks/$id'
import { Route as _authenticatedTasksIdIndexRouteImport } from './routes/__authenticated/tasks/$id/index'
import { Route as _authenticatedTasksIdReportRouteImport } from './routes/__authenticated/tasks/$id/report'
import { Route as _authenticatedTasksIdOverviewRouteImport } from './routes/__authenticated/tasks/$id/overview'
import { Route as _authenticatedTasksIdImportRouteImport } from './routes/__authenticated/tasks/$id/import'
import { Route as _authenticatedTasksIdExportRouteImport } from './routes/__authenticated/tasks/$id/export'
import { Route as _authenticatedTasksIdCleanRouteImport } from './routes/__authenticated/tasks/$id/clean'
import { Route as _authenticatedTasksIdAnalyzeRouteImport } from './routes/__authenticated/tasks/$id/analyze'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedRoute = _authenticatedRouteImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedIndexRoute = _authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedSettingsRoute = _authenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedTasksIndexRoute =
  _authenticatedTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedTasksIdRoute = _authenticatedTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedTasksIdIndexRoute =
  _authenticatedTasksIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _authenticatedTasksIdRoute,
  } as any)
const _authenticatedTasksIdReportRoute =
  _authenticatedTasksIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => _authenticatedTasksIdRoute,
  } as any)
const _authenticatedTasksIdOverviewRoute =
  _authenticatedTasksIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => _authenticatedTasksIdRoute,
  } as any)
const _authenticatedTasksIdImportRoute =
  _authenticatedTasksIdImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => _authenticatedTasksIdRoute,
  } as any)
const _authenticatedTasksIdExportRoute =
  _authenticatedTasksIdExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => _authenticatedTasksIdRoute,
  } as any)
const _authenticatedTasksIdCleanRoute =
  _authenticatedTasksIdCleanRouteImport.update({
    id: '/clean',
    path: '/clean',
    getParentRoute: () => _authenticatedTasksIdRoute,
  } as any)
const _authenticatedTasksIdAnalyzeRoute =
  _authenticatedTasksIdAnalyzeRouteImport.update({
    id: '/analyze',
    path: '/analyze',
    getParentRoute: () => _authenticatedTasksIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof _authenticatedIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof _authenticatedSettingsRoute
  '/tasks/$id': typeof _authenticatedTasksIdRouteWithChildren
  '/tasks/': typeof _authenticatedTasksIndexRoute
  '/tasks/$id/analyze': typeof _authenticatedTasksIdAnalyzeRoute
  '/tasks/$id/clean': typeof _authenticatedTasksIdCleanRoute
  '/tasks/$id/export': typeof _authenticatedTasksIdExportRoute
  '/tasks/$id/import': typeof _authenticatedTasksIdImportRoute
  '/tasks/$id/overview': typeof _authenticatedTasksIdOverviewRoute
  '/tasks/$id/report': typeof _authenticatedTasksIdReportRoute
  '/tasks/$id/': typeof _authenticatedTasksIdIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/settings': typeof _authenticatedSettingsRoute
  '/': typeof _authenticatedIndexRoute
  '/tasks': typeof _authenticatedTasksIndexRoute
  '/tasks/$id/analyze': typeof _authenticatedTasksIdAnalyzeRoute
  '/tasks/$id/clean': typeof _authenticatedTasksIdCleanRoute
  '/tasks/$id/export': typeof _authenticatedTasksIdExportRoute
  '/tasks/$id/import': typeof _authenticatedTasksIdImportRoute
  '/tasks/$id/overview': typeof _authenticatedTasksIdOverviewRoute
  '/tasks/$id/report': typeof _authenticatedTasksIdReportRoute
  '/tasks/$id': typeof _authenticatedTasksIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/__authenticated': typeof _authenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/__authenticated/settings': typeof _authenticatedSettingsRoute
  '/__authenticated/': typeof _authenticatedIndexRoute
  '/__authenticated/tasks/$id': typeof _authenticatedTasksIdRouteWithChildren
  '/__authenticated/tasks/': typeof _authenticatedTasksIndexRoute
  '/__authenticated/tasks/$id/analyze': typeof _authenticatedTasksIdAnalyzeRoute
  '/__authenticated/tasks/$id/clean': typeof _authenticatedTasksIdCleanRoute
  '/__authenticated/tasks/$id/export': typeof _authenticatedTasksIdExportRoute
  '/__authenticated/tasks/$id/import': typeof _authenticatedTasksIdImportRoute
  '/__authenticated/tasks/$id/overview': typeof _authenticatedTasksIdOverviewRoute
  '/__authenticated/tasks/$id/report': typeof _authenticatedTasksIdReportRoute
  '/__authenticated/tasks/$id/': typeof _authenticatedTasksIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/login'
    | '/settings'
    | '/tasks/$id'
    | '/tasks/'
    | '/tasks/$id/analyze'
    | '/tasks/$id/clean'
    | '/tasks/$id/export'
    | '/tasks/$id/import'
    | '/tasks/$id/overview'
    | '/tasks/$id/report'
    | '/tasks/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/login'
    | '/settings'
    | '/'
    | '/tasks'
    | '/tasks/$id/analyze'
    | '/tasks/$id/clean'
    | '/tasks/$id/export'
    | '/tasks/$id/import'
    | '/tasks/$id/overview'
    | '/tasks/$id/report'
    | '/tasks/$id'
  id:
    | '__root__'
    | '/$'
    | '/__authenticated'
    | '/login'
    | '/__authenticated/settings'
    | '/__authenticated/'
    | '/__authenticated/tasks/$id'
    | '/__authenticated/tasks/'
    | '/__authenticated/tasks/$id/analyze'
    | '/__authenticated/tasks/$id/clean'
    | '/__authenticated/tasks/$id/export'
    | '/__authenticated/tasks/$id/import'
    | '/__authenticated/tasks/$id/overview'
    | '/__authenticated/tasks/$id/report'
    | '/__authenticated/tasks/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  _authenticatedRoute: typeof _authenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/': {
      id: '/__authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _authenticatedIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/settings': {
      id: '/__authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof _authenticatedSettingsRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/tasks/': {
      id: '/__authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof _authenticatedTasksIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/tasks/$id': {
      id: '/__authenticated/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof _authenticatedTasksIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/tasks/$id/': {
      id: '/__authenticated/tasks/$id/'
      path: '/'
      fullPath: '/tasks/$id/'
      preLoaderRoute: typeof _authenticatedTasksIdIndexRouteImport
      parentRoute: typeof _authenticatedTasksIdRoute
    }
    '/__authenticated/tasks/$id/report': {
      id: '/__authenticated/tasks/$id/report'
      path: '/report'
      fullPath: '/tasks/$id/report'
      preLoaderRoute: typeof _authenticatedTasksIdReportRouteImport
      parentRoute: typeof _authenticatedTasksIdRoute
    }
    '/__authenticated/tasks/$id/overview': {
      id: '/__authenticated/tasks/$id/overview'
      path: '/overview'
      fullPath: '/tasks/$id/overview'
      preLoaderRoute: typeof _authenticatedTasksIdOverviewRouteImport
      parentRoute: typeof _authenticatedTasksIdRoute
    }
    '/__authenticated/tasks/$id/import': {
      id: '/__authenticated/tasks/$id/import'
      path: '/import'
      fullPath: '/tasks/$id/import'
      preLoaderRoute: typeof _authenticatedTasksIdImportRouteImport
      parentRoute: typeof _authenticatedTasksIdRoute
    }
    '/__authenticated/tasks/$id/export': {
      id: '/__authenticated/tasks/$id/export'
      path: '/export'
      fullPath: '/tasks/$id/export'
      preLoaderRoute: typeof _authenticatedTasksIdExportRouteImport
      parentRoute: typeof _authenticatedTasksIdRoute
    }
    '/__authenticated/tasks/$id/clean': {
      id: '/__authenticated/tasks/$id/clean'
      path: '/clean'
      fullPath: '/tasks/$id/clean'
      preLoaderRoute: typeof _authenticatedTasksIdCleanRouteImport
      parentRoute: typeof _authenticatedTasksIdRoute
    }
    '/__authenticated/tasks/$id/analyze': {
      id: '/__authenticated/tasks/$id/analyze'
      path: '/analyze'
      fullPath: '/tasks/$id/analyze'
      preLoaderRoute: typeof _authenticatedTasksIdAnalyzeRouteImport
      parentRoute: typeof _authenticatedTasksIdRoute
    }
  }
}

interface _authenticatedTasksIdRouteChildren {
  _authenticatedTasksIdAnalyzeRoute: typeof _authenticatedTasksIdAnalyzeRoute
  _authenticatedTasksIdCleanRoute: typeof _authenticatedTasksIdCleanRoute
  _authenticatedTasksIdExportRoute: typeof _authenticatedTasksIdExportRoute
  _authenticatedTasksIdImportRoute: typeof _authenticatedTasksIdImportRoute
  _authenticatedTasksIdOverviewRoute: typeof _authenticatedTasksIdOverviewRoute
  _authenticatedTasksIdReportRoute: typeof _authenticatedTasksIdReportRoute
  _authenticatedTasksIdIndexRoute: typeof _authenticatedTasksIdIndexRoute
}

const _authenticatedTasksIdRouteChildren: _authenticatedTasksIdRouteChildren = {
  _authenticatedTasksIdAnalyzeRoute: _authenticatedTasksIdAnalyzeRoute,
  _authenticatedTasksIdCleanRoute: _authenticatedTasksIdCleanRoute,
  _authenticatedTasksIdExportRoute: _authenticatedTasksIdExportRoute,
  _authenticatedTasksIdImportRoute: _authenticatedTasksIdImportRoute,
  _authenticatedTasksIdOverviewRoute: _authenticatedTasksIdOverviewRoute,
  _authenticatedTasksIdReportRoute: _authenticatedTasksIdReportRoute,
  _authenticatedTasksIdIndexRoute: _authenticatedTasksIdIndexRoute,
}

const _authenticatedTasksIdRouteWithChildren =
  _authenticatedTasksIdRoute._addFileChildren(
    _authenticatedTasksIdRouteChildren,
  )

interface _authenticatedRouteChildren {
  _authenticatedSettingsRoute: typeof _authenticatedSettingsRoute
  _authenticatedIndexRoute: typeof _authenticatedIndexRoute
  _authenticatedTasksIdRoute: typeof _authenticatedTasksIdRouteWithChildren
  _authenticatedTasksIndexRoute: typeof _authenticatedTasksIndexRoute
}

const _authenticatedRouteChildren: _authenticatedRouteChildren = {
  _authenticatedSettingsRoute: _authenticatedSettingsRoute,
  _authenticatedIndexRoute: _authenticatedIndexRoute,
  _authenticatedTasksIdRoute: _authenticatedTasksIdRouteWithChildren,
  _authenticatedTasksIndexRoute: _authenticatedTasksIndexRoute,
}

const _authenticatedRouteWithChildren = _authenticatedRoute._addFileChildren(
  _authenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  _authenticatedRoute: _authenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
