"""add document channel and size_bytes

Revision ID: a1c3e5f7b9d2
Revises: 79b320f02b84
Create Date: 2026-06-22 06:30:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a1c3e5f7b9d2'
down_revision: Union[str, Sequence[str], None] = '79b320f02b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('channel', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'size_bytes')
    op.drop_column('documents', 'channel')
    # ### end Alembic commands ###
