"""add task employee and archive fields

Revision ID: 79b320f02b84
Revises: 2db162623360
Create Date: 2026-06-22 04:51:31.793475+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79b320f02b84'
down_revision: Union[str, Sequence[str], None] = '2db162623360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('employee_name', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('employee_id', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('audit_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('audit_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('expected_channels', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.add_column('tasks', sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'archived')
    op.drop_column('tasks', 'expected_channels')
    op.drop_column('tasks', 'audit_end')
    op.drop_column('tasks', 'audit_start')
    op.drop_column('tasks', 'department')
    op.drop_column('tasks', 'employee_id')
    op.drop_column('tasks', 'employee_name')
    # ### end Alembic commands ###
